name: Build Android APK

on:
  push:
    branches: [ principal, main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev lldb lld zlib1g-dev zip unzip autoconf libtool pkg-config openjdk-17-jdk

    - name: Install Python Dependencies
      run: |
        pip install --upgrade pip
        pip install cython virtualenv
        pip install git+https://github.com/kivy/buildozer.git

    - name: Force Android SDK Version 34
      run: |
        # On crée le dossier en avance pour forcer Buildozer à utiliser l'API 34 stable
        mkdir -p ~/.buildozer/android/platform/
        echo "android.api = 34" >> buildozer.spec
        echo "android.build_tools_version = 34.0.0" >> buildozer.spec

    - name: Build with Buildozer
      run: |
        buildozer android debug
      env:
        APP_ANDROID_ACCEPT_SDK_LICENSE: "y"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-debug
        path: bin/*.apk
